/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

}

declare global {
  interface StencilElementInterfaces {

  }

  interface StencilIntrinsicElements {

  }



  interface HTMLElementTagNameMap {

  }

  interface ElementTagNameMap {

  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
